version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jaguarete
      MYSQL_USER: unida
      MYSQL_PASSWORD: unida123
    volumes:
      - C:/mysql_data:/var/lib/mysql

  python-app:
    build: ./app
    container_name: python-app-container
    volumes:
      - C:\Users\neara\Desktop\python curso\clase 5\app
    ports:
      - "5001:5001"
    depends_on:
      - mysql
